### ISSUE TITLE
Updates will change items in code fences when identical to other, normal items

### ISSUE THREAD

**Issue by mtodd** [github-archive/task_list#45]
While we [normally skip task list items embedded in code fences for updates](https://github.com/github/task_list/blob/be013973bf0780d8934f599285fbb7083bce06f9/app/assets/javascripts/task_list.coffee#L167-L168), we rely on code fence items being unique from items outside of code fences. This can result in updates matching items in code fences and updating those instead.

Reproduction:

``````
```
- [ ] identical
```
- identical
``````

No immediate remediation steps known.

**Comment by deckar01** [comment]
This issue was moved to deckar01/task_list#3
