### ISSUE TITLE
Checkboxes don't check when inside an unordered list.

### ISSUE THREAD

**Issue by kyletolle** [github-archive/task_list#56]
I have a list that's structured like this. I'm trying to use checkboxes in an unordered list.

```
- One
  - - [ ] A
  - - [ ] B
- Two
  - - [ ] C
  - - [ ] D
```

Here it is, rendered:
- One
  - \- [ ] A
  - \- [ ] B
- Two
  - \- [ ] C
  - \- [ ] D

And it renders properly with checkboxes indented in the list. So that's cool.

But what doesn't work is checking any of the boxes from the web UI.

I check the box and it shows the checkmark when I have the mouse pressed down. But when I let up, there check box is blank again. No errors in the Chrome dev console.

Using Chrome Version 41.0.2272.89 (64-bit) on OS X 10.10.2.

My workaround for this is to edit the comment and manually change it from `- [ ]` to `- [x]`.

Thanks for your help.

**Comment by deckar01** [comment]
This issue was moved to deckar01/task_list#5
