### ISSUE TITLE
Broken checkbox at list

### ISSUE THREAD

**Issue by marcosrjjunior** [github-archive/task_list#62]
### Issue Example

If add checkbox at list and remove space inside '[ ]' it breaks

![githubmarkdown2](https://cloud.githubusercontent.com/assets/5287262/9037976/e5bb078e-39c6-11e5-8ceb-dab9901e08be.png)
![githubmarkdown1](https://cloud.githubusercontent.com/assets/5287262/9037977/e5bbead2-39c6-11e5-9ef6-3d1fbce1994e.png)

Here without removing the spaces  
1. Test Test
2. Test Test
   -[ ] Test  
### Gist Example

In this example, it is breaking even without removing the spaces
https://gist.github.com/marcosrjjunior/aa3cd1239050876193dd

**Comment by deckar01** [comment]
This issue was moved to deckar01/task_list#6
