### ISSUE TITLE
rendering of task lists with german keyboard layout

### ISSUE THREAD

**Issue by thojansen** [github-archive/task_list#64]
I just noticed that the rendering of task lists does not work correctly when using a german keyboard layout. It eventually work after re-editing the comment a few times at some point, but the effect can be seen as follows.

typed with a german keyboard layout
- [ ] item1
- [ ] item2

switched to an english keyboard layout
- [ ] item 1
- [ ] item2

Any idea what happens here and why this breaks?

**Comment by deckar01** [comment]
This issue was moved to deckar01/task_list#7
